/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package progym.vista.dialogos;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import progym.logica.basica.daos.RutinaController;
import progym.logica.basica.util.Fecha;
import progym.logica.basica.util.IdentifyRutina;
import progym.recursos.graficas.GraficaBarDataset;

/**
 *
 * @author Ariel Jose Arnedo
 */
public class DialogoChartInfo extends javax.swing.JDialog {

    private static final Font FONT_TITLE = new Font("Arial",1,15);
    private static final Color COLOR_CORRECT = Color.CYAN;
    
    
    public DialogoChartInfo(java.awt.Frame parent) {
        super(parent, true);
        this.setTitle("Rendimiento");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/progym/recursos/imagenes/icon_DialogChart32x32.png")));
        initComponents();
        this.setLocation(100,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPestaña = new javax.swing.JTabbedPane();
        rendimientoGlobal = new javax.swing.JPanel();
        panelSeleccion = new javax.swing.JPanel();
        panelGraficaGlobal = new org.jdesktop.swingx.JXTitledPanel();
        redimientoGlobal = new javax.swing.JPanel();
        panelSeleccion1 = new javax.swing.JPanel();
        panelGraficaMensual = new org.jdesktop.swingx.JXTitledPanel();
        redimientoActual = new javax.swing.JPanel();
        panelGraficaActual = new org.jdesktop.swingx.JXTitledPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelPestaña.setMinimumSize(new java.awt.Dimension(500, 300));
        panelPestaña.setPreferredSize(new java.awt.Dimension(850, 500));

        rendimientoGlobal.setLayout(new java.awt.BorderLayout());

        grupo=new javax.swing.ButtonGroup();

        try{
            for(int i=0;i<IdentifyRutina.getIdentitifyRutina().getNameRutinas().size();i++){
                javax.swing.JRadioButton boton=new javax.swing.JRadioButton(IdentifyRutina.getIdentitifyRutina().getNameRutinas().get(i));
                boton.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt){
                        botonSeleccionAccionOcurrida(evt);
                    }
                });
                grupo.add(boton);
                panelSeleccion.add(boton);
            }
        }catch(Exception ex){
            panelSeleccion.add(new javax.swing.JLabel("Error al Leer las Rutinas"));
        }

        rendimientoGlobal.add(panelSeleccion, java.awt.BorderLayout.NORTH);
        rendimientoGlobal.add(panelGraficaGlobal, java.awt.BorderLayout.CENTER);

        panelPestaña.addTab("Rendimiento Global", rendimientoGlobal);

        redimientoGlobal.setLayout(new java.awt.BorderLayout());

        grupo1=new javax.swing.ButtonGroup();

        try{
            for(int i=0;i<IdentifyRutina.getIdentitifyRutina().getNameRutinas().size();i++){
                javax.swing.JRadioButton boton=new javax.swing.JRadioButton(IdentifyRutina.getIdentitifyRutina().getNameRutinas().get(i));
                boton.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt){
                        botonSeleccion1AccionOcurrida(evt);
                    }
                });
                grupo1.add(boton);
                panelSeleccion1.add(boton);
            }
        }catch(Exception ex){
            panelSeleccion1.add(new javax.swing.JLabel("Error al Leer las Rutinas"));
        }

        redimientoGlobal.add(panelSeleccion1, java.awt.BorderLayout.NORTH);
        redimientoGlobal.add(panelGraficaMensual, java.awt.BorderLayout.CENTER);

        panelPestaña.addTab("Rendimiento Mensual", redimientoGlobal);

        redimientoActual.setLayout(new java.awt.BorderLayout());

        try{
            panelGraficaActual.setTitleFont(FONT_TITLE);
            panelGraficaActual.setTitle("Rendimiento de la Rutina actual "+IdentifyRutina.getIdentitifyRutina().getRutinaActual());
            panelGraficaActual.setTitleForeground(COLOR_CORRECT);
            panelGraficaActual.add(createChartPanel());
        }catch(Exception e){
            panelGraficaActual.setTitle("Error al Leer la Rutina Actual");
            panelGraficaActual.setTitleForeground(Color.RED);
        }

        redimientoActual.add(panelGraficaActual, java.awt.BorderLayout.CENTER);

        panelPestaña.addTab("Rendimiento Actual", redimientoActual);

        getContentPane().add(panelPestaña, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        panelGraficaGlobal.setTitleFont(FONT_TITLE);
        panelGraficaMensual.setTitleFont(FONT_TITLE);
    }//GEN-LAST:event_formWindowOpened

   
    private void botonSeleccionAccionOcurrida(java.awt.event.ActionEvent evt){
        final String rutinaSelecionada=((javax.swing.JRadioButton)evt.getSource()).getText();
        final GraficaBarDataset graficaGlobal=new GraficaBarDataset("Rendimiento");
        Component compo = panelGraficaGlobal.getContentContainer();
        if(compo != null){
            panelGraficaGlobal.remove(compo);
        }
        panelGraficaGlobal.repaint();
        final Runnable run = new Runnable(){
            @Override
            public void run(){
                Enumeration<AbstractButton> botones = DialogoChartInfo.this.grupo.getElements();
                while(botones.hasMoreElements()){
                    if(botones.nextElement().getText().compareTo(rutinaSelecionada)==0){
                        try{
                            
                            graficaGlobal.setDatos(new RutinaController().getRutinaNombre(rutinaSelecionada));
                            panelGraficaGlobal.setContentContainer(graficaGlobal.getGrafica("Fecha"));
                            panelGraficaGlobal.setTitle("Rendimiento Global Rutina "+rutinaSelecionada);
                            
                        }catch(SQLException ex){
                            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                            return;
                        }
                    }
                }
            }
        };
        Thread hilo=new Thread(run);
        hilo.start();
        
    }
    
    private void botonSeleccion1AccionOcurrida(java.awt.event.ActionEvent evt){
        
    }
    
    private JComponent createChartPanel(){
        String rutinaActual;
        try {
            rutinaActual = IdentifyRutina.getIdentitifyRutina().getNameFechaActual();
        } catch (Exception ex) {
            JLabel eti = new JLabel("ERROR AL PROCESAR EL NOMBRE DE LA RUTINA ACTUAL");
            eti.setFont(FONT_TITLE);
            eti.setForeground(Color.red);
            return eti;
        }
        final GraficaBarDataset graficaGlobal=new GraficaBarDataset("Rendimiento");
        try{
           graficaGlobal.setDatos(new RutinaController().getRutina(Fecha.getCodFechaRutina()));
           return graficaGlobal.getGrafica("Fecha");
        }catch(SQLException ex){
            JLabel eti = new JLabel("ERROR, AUN NO SE TIENE REGISTRO DE LA SERIES DE LA RUTINA ACTUAL EN LA BASE DE DATOS");
            eti.setFont(FONT_TITLE);
            eti.setForeground(Color.red);
            return eti;
        }
    }
    
    private javax.swing.ButtonGroup grupo;
    private javax.swing.ButtonGroup grupo1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTitledPanel panelGraficaActual;
    private org.jdesktop.swingx.JXTitledPanel panelGraficaGlobal;
    private org.jdesktop.swingx.JXTitledPanel panelGraficaMensual;
    private javax.swing.JTabbedPane panelPestaña;
    private javax.swing.JPanel panelSeleccion;
    private javax.swing.JPanel panelSeleccion1;
    private javax.swing.JPanel redimientoActual;
    private javax.swing.JPanel redimientoGlobal;
    private javax.swing.JPanel rendimientoGlobal;
    // End of variables declaration//GEN-END:variables
}
